#! /usr/bin/env lua

local result = ...

local function quote(s)
  return [[']]..s:gsub([[']], [['\'']])..[[']]
end

local command = ("openssl ecparam -genkey -name prime256v1 -noout -out %s"):format(quote(result))
assert(os.execute(command))

local command = ("openssl ec -in %s -pubout -outform DER | tail -c 65 | base64"):format(quote(result))
local handle = assert(io.popen(command))
local data = handle:read "*a"
assert(handle:close())

local handle = assert(io.open(result..".pub", "w"))
-- -----BEGIN PUBLIC KEY-----
-- -----END PUBLIC KEY-----

data = data
  :gsub("^%-+BEGIN PUBLIC KEY%-+\n", "")
  :gsub("%-+END PUBLIC KEY%-+\n$", "")
  :gsub("\n", "")
  :gsub("=*$", "")
  :gsub("%+", "-")
  :gsub("/", "_")
handle:write(data)
assert(handle:close())
